# Generated by Django 5.2 on 2025-04-09 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='total_number_of_listening',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='total_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
